version: 2
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:4.8.6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g -i'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: upload to codecov
          command: npm run codecov
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml